name: Setup ngrok and Remote Desktop (Self-Hosted 32GB / 28 cores)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  setup-ngrok:
    runs-on: self-hosted  # Your custom runner
    timeout-minutes: 720  # 12 hours runtime

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify System Resources
        run: |
          Write-Host "🔍 Checking system specs..."
          Get-ComputerInfo | Select-Object CsTotalPhysicalMemory, CsNumberOfLogicalProcessors
          Write-Host "✅ Target Specs: 32GB RAM, 28 cores (make sure your runner matches)"

      - name: Download ngrok (with retry)
        run: |
          $retry = 3
          while ($retry -gt 0) {
            try {
              Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip -UseBasicParsing
              if (Test-Path ngrok.zip) { break }
            } catch {
              Write-Host "Retrying download... ($retry left)"
            }
            Start-Sleep -Seconds 5
            $retry--
          }
          if (!(Test-Path ngrok.zip)) { throw "❌ Failed to download ngrok after retries." }

      - name: Extract ngrok
        run: |
          Expand-Archive ngrok.zip -DestinationPath .
          if (!(Test-Path .\ngrok.exe)) { throw "❌ Failed to extract ngrok." }

      - name: Update ngrok
        run: .\ngrok.exe update

      - name: Authenticate ngrok
        run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable Remote Desktop
        run: |
          Write-Host "🖥 Enabling Remote Desktop..."
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1

      - name: Set Password for runneradmin
        run: |
          $user = Get-LocalUser -Name "runneradmin"
          if ($user.Enabled -eq $false) { Enable-LocalUser -Name "runneradmin" }
          $secPass = ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $secPass
          Write-Host "🔐 Password set successfully!"

      - name: Start ngrok TCP tunnel (RDP port)
        run: |
          Write-Host "🚀 Starting ngrok tunnel..."
          Start-Process -FilePath .\ngrok.exe -ArgumentList "tcp 3389 --log=stdout > ngrok.log" -WindowStyle Hidden
          Start-Sleep -Seconds 10
          Get-Content ngrok.log -ErrorAction SilentlyContinue

      - name: Display connection info
        run: |
          $apiUrl = "http://127.0.0.1:4040/api/tunnels"
          try {
            $response = Invoke-RestMethod -Uri $apiUrl
            $tcpAddr = ($response.tunnels | Where-Object { $_.proto -eq "tcp" }).public_url
            if ($tcpAddr) {
              Write-Output "✅ Connect via RDP: $tcpAddr"
              Write-Output "👤 Username: runneradmin"
              Write-Output "🔑 Password: P@ssw0rd!"
            } else {
              Write-Output "⚠️ Tunnel not active yet."
            }
          } catch {
            Write-Output "⚠️ Ngrok API not responding."
          }

      - name: Keep Alive (12 hours)
        run: |
          for ($i = 0; $i -lt 144; $i++) {
            Write-Host "⏳ Still alive... Minute: $($i * 5)"
            Start-Sleep -Seconds 300
          }
        continue-on-error: true
